# We create a database named as superstore_database.
CREATE DATABASE superstore_database;

# Used database name is used to change the directory to the specified directory.
USE superstore_database;

# Describe table name is used to see the structure of table like column name,datatypes,keys,null values etc.
DESC superstore_raw;

# SELECT * FROM table_name is used to retrieve all the values from the table and LIMIT is used to add an upper limit to output.
SELECT * FROM superstore_raw
LIMIT 10;

# CREATE TABLE table_name through this query we have created a table named customers with columns customer_id and customer_name.
CREATE TABLE customers(
customer_id VARCHAR(50),
customer_name VARCHAR(100)
);

# Through DISTINCT keyword we have inserted unique customer records from the raw dataset into the customers table.
INSERT INTO customers (customer_id, customer_name)
SELECT DISTINCT
    `Customer ID`,
    `Customer Name`
FROM superstore_raw;

# Through this query we have created a table named products which containns product info like product_id, product_name, category.
CREATE TABLE products (
    product_id VARCHAR(50),
    product_name VARCHAR(255),
    category VARCHAR(100)
);

# Through DISTINCT keyword we have inserted unique product records from the raw dataset into the products table.
INSERT INTO products
SELECT DISTINCT
    `Product ID`,
    `Product Name`,
    Category
FROM superstore_raw;

# Through this query we have created a table named orders which contains order info like order_id, customer_id, product_id, order_date, sales.
CREATE TABLE orders (
    order_id VARCHAR(30),
    customer_id VARCHAR(20),
    product_id VARCHAR(50),
    order_date DATE,
    sales DECIMAL(10,2)
);

# Through DISTINCT keyword we have inserted unique order records from the raw dataset into the orders table.
INSERT INTO orders
SELECT DISTINCT
    `Order ID`,
    `Customer ID`,
    `Product ID`,
    STR_TO_DATE(`Order Date`, '%m/%d/%Y'),
    Sales
FROM superstore_raw;

# Used to display order dates form the raw dataset.
SELECT `Order Date` 
FROM superstore_raw
LIMIT 5;

# Subquery
# Used to find orders whose sales value is greater than the average sales.
SELECT * FROM orders
WHERE Sales >(SELECT AVG(Sales) FROM orders);

# Used to find the highest sales order placed by each customer.
SELECT * FROM orders
WHERE sales IN (SELECT MAX(sales) FROM orders GROUP BY customer_id
);

# CTE
# Used to calculate total sales generated by each customer using a CTE.
WITH customer_sales AS
(
SELECT customer_id,
SUM(Sales) AS TotalSales
FROM orders
GROUP BY customer_id
)
SELECT *
FROM customer_sales;

# CTE + Subquery
# Used to display customers whose total sales are above the average customer sales.
WITH customer_sales AS(
SELECT customer_id,
SUM(Sales) AS TotalSales
FROM orders
GROUP BY customer_id
)
SELECT *
FROM customer_sales
WHERE TotalSales >(
SELECT AVG(TotalSales)
FROM customer_sales
);

# Window function 
# Used to rank customers based on their total sales in descending order.
SELECT customer_id,
SUM(Sales) AS TotalSales,
RANK() OVER(
ORDER BY SUM(Sales) DESC
) AS RankNo
FROM orders
GROUP BY customer_id;

# Window function + PARTITION BY
# Used to assign a row number to each order within every customer group.
SELECT customer_id,
order_id,
Sales,
ROW_NUMBER() OVER(
PARTITION BY customer_id
ORDER BY Sales DESC
) AS RowNum
FROM orders;

# Window function 
# Used to retrieve the top 3 customers based on total sales.
WITH customer_sales AS(
SELECT customer_id,
SUM(Sales) AS TotalSales,
RANK() OVER(
ORDER BY SUM(Sales) DESC
) AS RankNo FROM orders
GROUP BY customer_id
)
SELECT * FROM customer_sales
WHERE RankNo <= 3;

# Final Combined Query
# JOIN + CTE + Window Function
# Used to display customer ID, total sales, and sales rank using CTE, JOIN, and Window Function.
WITH customer_sales AS(
SELECT customer_id,
SUM(Sales) AS TotalSales
FROM orders
GROUP BY customer_id
)
SELECT c.customer_id,
cs.TotalSales,
RANK() OVER(
ORDER BY cs.TotalSales DESC
) AS RankNo
FROM customer_sales cs
JOIN customers c
ON cs.customer_id = c.customer_id;

# Mini project : Customer sales insides 
# Used to find the top 5 customers based on total sales.
SELECT `Customer Name`,
SUM(Sales) AS TotalSales
FROM superstore_raw
GROUP BY `Customer Name`
ORDER BY TotalSales DESC
LIMIT 5;

# Used to find the bottom 5 customers based on total sales.
SELECT `Customer Name`,
SUM(Sales) AS TotalSales
FROM superstore_raw
GROUP BY `Customer Name`
ORDER BY TotalSales ASC
LIMIT 5;

# Used to identify customers who have placed only one order.
SELECT `Customer Name`
FROM superstore_raw
GROUP BY `Customer Name`
HAVING COUNT(DISTINCT `Order ID`) = 1;

# Used to find customers whose total sales are above the overall average sales.
SELECT `Customer Name`,
SUM(Sales) AS TotalSales
FROM superstore_raw
GROUP BY `Customer Name`
HAVING SUM(Sales) >(
SELECT AVG(Sales)
FROM superstore_raw
);

# Used to display the highest order value recorded for each customer.
SELECT `Customer Name`,
MAX(Sales) AS HighestOrder
FROM superstore_raw
GROUP BY `Customer Name`;

